import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:provider/provider.dart';

class LanguageManager with ChangeNotifier {
  static final LanguageManager _instance = LanguageManager._internal();
  factory LanguageManager() => _instance;
  LanguageManager._internal();

  Locale _currentLocale = const Locale('tr', 'TR');
  Locale get currentLocale => _currentLocale;

  static const String TR = 'tr';
  static const String EN = 'en';

  // --- TTRPG UYGULAMASI İÇİN ÇEVİRİ SÖZLÜĞÜ ---
  final Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      // --- TÜRKÇE ANAHTARLAR (UI'da Türkçe yazılmış olanlar) ---
      'Kayıt Başarılı!': 'Kayıt Başarılı!',
      'Kayıt Başarısız! Sunucuyu kontrol edin.': 'Kayıt Başarısız! Sunucuyu kontrol edin.',
      'Hatalı email veya şifre!': 'Hatalı email veya şifre!',
      'Oyuna bağlama': 'Oyuna bağlama',
      'Vazgeç': 'Vazgeç',
      'İsim, Irk ve Sınıf alanları zorunludur.': 'İsim, Irk ve Sınıf alanları zorunludur.',
      'Kaydet': 'Kaydet',
      'Kapat': 'Kapat',
      'İptal': 'İptal',
      'Oyun Başarıyla Oluşturuldu!': 'Oyun Başarıyla Oluşturuldu!',
      'Harita başarıyla veritabanına eklendi!': 'Harita başarıyla veritabanına eklendi!',
      'Hata oluştu!': 'Hata oluştu!',
      'Önbellek başarıyla temizlendi!': 'Önbellek başarıyla temizlendi!',
      'Ayarlar': 'Ayarlar',
      'Türkçe': 'Türkçe',
      'English': 'English',
      'Aydınlık veya karanlık mod': 'Aydınlık veya karanlık mod',
      'Geçici verileri siler': 'Geçici verileri siler',
      'Çıkış Yap': 'Çıkış Yap',
      'Hesabınızdan çıkış yapmak istediğinize emin misiniz?': 'Hesabınızdan çıkış yapmak istediğinize emin misiniz?',
      'Login': 'Giriş Yap',
      'Register': 'Kayıt Ol',
      'Game Master': 'Oyun Yöneticisi (GM)',
      'Player': 'Oyuncu',
      'Passwords do not match!': 'Şifreler eşleşmiyor!',
      'Please fill all fields': 'Lütfen tüm alanları doldurun',
      'Game successfully updated!': 'Oyun başarıyla güncellendi!',
      'Update failed. Try again later.': 'Güncelleme başarısız. Sonra tekrar deneyin.',
      'Game invitation code': 'Oyun davet kodu',
      'Max Player:': 'Maks. Oyuncu:',
      'Public Game': 'Açık Oyun (Public)',
      'Save Changes': 'Değişiklikleri Kaydet',
      'Finish Campaing': 'Serüveni Bitir',
      'Are you sure you want to finish this campaign? This action cannot be undone!': 'Bu serüveni bitirmek istediğinize emin misiniz? Bu işlem geri alınamaz!',
      'Yes, end the game': 'Evet, oyunu bitir',
      'Game successfully finished!': 'Oyun başarıyla bitirildi!',
      'End Campaing': 'Serüveni Sonlandır',
      'Linked Maps': 'Bağlı Haritalar',
      'Firstly a map has to be added to map pool!': 'Öncelikle harita havuzuna bir harita eklenmeli!',
      'Map linked!': 'Harita bağlandı!',
      'No maps has been linked to this game.': 'Bu oyuna henüz harita bağlanmamış.',
      'Game records & Notes': 'Oyun Kayıtları ve Notlar',
      'Firstly a note has to be added to note pool!': 'Öncelikle not havuzuna bir not eklenmeli!',
      'Added': 'Eklendi',
      'Error occured while adding the note.': 'Not eklenirken bir hata oluştu.',
      'No notes has been added yet to this game.': 'Bu oyuna henüz not eklenmemiş.',
      'New Note': 'Yeni Not',
      'Delete Note?': 'Not Silinsin mi?',
      'Are you sure you want to delete this note?': 'Bu notu silmek istediğinize emin misiniz?',
      'Cancel': 'İptal',
      'Delete': 'Sil',
      'Back': 'Geri',
      'Edit': 'Düzenle',
      'Create New Campaign': 'Yeni Serüven Oluştur',
      'Max Players:': 'Maks. Oyuncu:',
      'Visible to everyone in search results': 'Arama sonuçlarında herkese görünür',
      'Create Campaign': 'Serüven Oluştur',
      'Game Archive': 'Oyun Arşivi',
      'Adventurers': 'Maceracılar',
      'No players have joined this game.': 'Bu oyuna henüz oyuncu katılmamış.',
      'Discovered Realms': 'Keşfedilen Diyarlar',
      'No maps have been added for this game.': 'Bu oyun için henüz harita eklenmemiş.',
      'Game Records & Notes': 'Oyun Kayıtları ve Notlar',
      'No note added for this campaign!': 'Bu serüven için not eklenmemiş!',
      'No maps has been added yet.': 'Henüz harita eklenmemiş.',
      'No notes has been added yet.': 'Henüz not eklenmemiş.',
      'See all notes': 'Tüm notları gör',
      'My Games': 'Oyunlarım',
      'Add New Map': 'Yeni Harita Ekle',
      'Pick from gallery': 'Galeriden seç',
      'Enter URL': 'URL gir',
      'Open gallery': 'Galeriyi Aç',
      'Add map to pool': 'Haritayı havuza ekle',
      'Map Pool': 'Harita Havuzu',
      'You have successfully joined the game!': 'Oyuna başarıyla katıldınız!',
      'Find Games': 'Oyun Bul',
      'Join': 'Katıl',
      'No public games have been created yet.': 'Henüz açık (public) bir oyun oluşturulmamış.',
      'My Joined Games': 'Katıldığım Oyunlar',
      'No notes have been created yet.': 'Henüz hiç not oluşturulmamış.',
      'Game Details': 'Oyun Detayları',
      'GM has not added a map to this game yet.': 'GM bu oyuna henüz harita eklememiş.',
      'CORE FEATURES': 'TEMEL ÖZELLİKLER',
      'CLASS PROGRESSION': 'SINIF GELİŞİMİ',
      'Rule Books': 'Kural Kitapları',
      'No data found.': 'Veri bulunamadı.',
      'CORE RULES & GUIDES': 'TEMEL KURALLAR VE REHBERLER',
      'Dil / Language': 'Dil',
      'Karanlık Tema': 'Tema',
      'Önbelleği Temizle': 'Önbellek temizle',
      'Change to GM View': 'Oyun Yöneticisi (GM) Görünümüne Geç',
      'Change to Player View': 'Oyuncu Görünümüne Geç',
      'Notes': 'Notlar',
      'Characters': 'Karakterler',
      'Create Game': 'Oyun Oluştur',
      'My Maps': 'Haritalarım',
      'Logout': 'Çıkış Yap',
      'Settings': 'Ayarlar',
      'Join Game': 'Oyuna Katıl',
      'NPCs': 'NPCler',
      'Games': 'Oyunlar',
      'Maps': 'Haritalar',
      'NPC Ekle': 'NPC Ekle',
      'Karakter Ekle': 'Karakter Ekle',
      'Karakter Resmi (Opsiyonel)': 'Karakter Resmi (Opsiyonel)',
      'İsim *': 'İsim *',
      'Örn: Gandalf, Aragorn': 'Örn: Gandalf, Aragorn',
      'Irk (Race) *': 'Irk (Race) *',
      'Sınıf (Class) *': 'Sınıf (Class) *',
      'Seviye:': 'Seviye:',
      'Background': 'Geçmiş (Background)',
      'Alignment': 'Hizalama (Alignment)',
      'Oyun (opsiyonel)': 'Oyun (Opsiyonel)',
      'Ability Scores': 'Ability Scores',
      'Standart: 10 | Modifier otomatik hesaplanır': 'Standart: 10 | Modifier otomatik hesaplanır',
      'Combat Stats': 'Combat Stats',
      'Backstory (hikaye)': 'Backstory (Hikaye)',
      'Karakterin geçmişi, motivasyonu...': 'Karakterin geçmişi, motivasyonu...',
      'NPC eklendi!': 'NPC eklendi!',
      'Karakter eklendi!': 'Karakter eklendi!',
      'Kayıt sırasında hata oluştu.': 'Kayıt sırasında hata oluştu.',
      'Karakterlerim': 'Karakterlerim',
      'Henüz NPC eklenmemiş.': 'Henüz NPC eklenmemiş.',
      'Henüz karakter eklenmemiş.': 'Henüz karakter eklenmemiş.',
      '+ butonuna basarak oluşturabilirsin!': '+ butonuna basarak oluşturabilirsin!',
      'Irk': 'Irk',
      'Sınıf': 'Sınıf',
      'Seviye': 'Seviye',
      'Backstory': 'Backstory',
      'Join to a Private Game': 'Özel Bir Oyuna Katıl',
      'Ex: A7X9BQ': 'Örn: A7X9BQ',
      'Public Games': 'Herkese Açık Oyunlar',
      'No description...': 'Açıklama yok...',
      'Your Game': 'Senin Oyunun',
      'Already Joined': 'Zaten Katıldın',
      'World is full': 'Oda Dolu',
      'GM Notes': 'GM Notları',
      'Player Notes': 'Oyuncu Notları',
      'No adventure notes yet.': 'Henüz macera notu yok.',
      'Tap + to record your journey!': 'Yolculuğunu kaydetmek için + butonuna bas!',
      'New GM Entry': 'Yeni GM Kaydı',
      'New Player Log': 'Yeni Oyuncu Kaydı',
      'Title': 'Başlık',
      'e.g. The Mysterious Stranger': 'Örn. Gizemli Yabancı',
      'Category': 'Kategori',
      'Sub-Category (Optional)': 'Alt Kategori (İsteğe Bağlı)',
      'Details': 'Detaylar',
      'Write down what happened...': 'Neler yaşandığını buraya yaz...',
      'NPC': 'YZK (NPC)',
      'Quest': 'Görev',
      'Loot': 'Ganimet',
      'Location': 'Mekan',
      'Combat': 'Savaş',
      'Other': 'Diğer',
      'Villager': 'Köylü',
      'Merchant': 'Tüccar',
      'Guard': 'Muhafız',
      'Noble': 'Soylular',
      'Wizard': 'Büyücü',
      'Monster': 'Canavar',
      'Main Story': 'Ana Hikaye',
      'Side Quest': 'Yan Görev',
      'Bounty': 'Ödül Avı',
      'Escort': 'Koruma',
      'Gathering': 'Toplama',
      'Weapon': 'Silah',
      'Armor': 'Zırh',
      'Consumable': 'Tüketilebilir',
      'Gold/Valuables': 'Altın/Değerli Eşya',
      'Artifact': 'Kalıntı (Artifact)',
      'Village': 'Köy',
      'City': 'Şehir',
      'Cave': 'Mağara',
      'Dungeon': 'Zindan',
      'Forest': 'Orman',
      'Tavern': 'Taverna',
      'Encounter': 'Karşılaşma',
      'Boss Fight': 'Boss Savaşı',
      'Trap': 'Tuzak',
      'Ambush': 'Pusu',
      'Lore': 'Evren (Lore)',
      'Rumor': 'Söylenti',
      'Puzzle': 'Bulmaca',
      'Misc': 'Çeşitli',
      'Campaign Title': 'Serüven Başlığı',
      'Description': 'Açıklama',
      'Map Name': 'Harita Adı',
      'Image URL': 'Resim URL\'si',
      'No maps have been added yet.': 'Henüz harita eklenmemiş.',
      'Story has not been told...': 'Hikaye henüz anlatılmadı...',
      'Unknown Hero': 'İsimsiz Kahraman',
      'Nameless Note': 'İsimsiz Not',
      'Players': 'Oyuncu',
      'Public': 'Açık (Public)',
      'Private': 'Gizli (Private)',
      'No games have been created yet.': 'Henüz hiç oyun oluşturulmadı.',
      'Edit game': 'Oyunu Düzenle',
      'Copy code': 'Kodu Kopyala',
      'Game Name': 'Oyun Adı',
      'Story / Description': 'Hikaye / Açıklama',
      'Oyuncu': 'Oyuncu',
      'Lv.': 'Lv.',
      'Races': 'Irklar',
      'Explore the diverse peoples of the world': 'Dünyanın çeşitli halklarını keşfedin',
      'Classes': 'Sınıflar',
      'Choose your path and abilities': 'Yolunuzu ve yeteneklerinizi seçin',
      'Equipment': 'Ekipmanlar',
      'Weapons, armor, tools, and adventuring gear': 'Silahlar, zırhlar, araçlar ve macera eşyaları',
      'Monsters': 'Canavarlar',
      'Creatures, stats, legendary actions, and beasts': 'Yaratıklar, istatistikler, efsanevi eylemler ve canavarlar',
      'Spells': 'Büyüler',
      'Master the arcane and divine arts': 'Gizemli ve ilahi sanatlarda ustalaşın',
      'Everything you need to know about slots, concentration and components.': 'Büyü yuvaları, odaklanma ve bileşenler hakkında bilmeniz gereken her şey.',
      'Core rules for armor, weapons, wealth, and item management.': 'Zırh, silah, servet ve eşya yönetimi için temel kurallar.',
      'Rules for creature stats, sizes, challenge ratings, and actions.': 'Yaratık istatistikleri, boyutları, zorluk dereceleri ve eylemleri için kurallar.',
      'Essential mechanics and shared traits every player should know.': 'Her oyuncunun bilmesi gereken temel mekanikler ve ortak özellikler.',
      'Email': 'E-posta',
      'Password': 'Şifre',
      'Select Role': 'Rol Seç',
      'Don\'t have an account? Register': 'Hesabın yok mu? Kayıt Ol',
      'Username': 'Kullanıcı Adı',
      'Confirm Password': 'Şifreyi Onayla',
      'Already registered? Log in': 'Zaten kayıtlı mısın? Giriş Yap',
    },

    'en': {
      // --- TÜRKÇE ANAHTARLAR (UI'da Türkçe yazılmış olanların EN karşılığı) ---
      'Kayıt Başarılı!': 'Registration Successful!',
      'Kayıt Başarısız! Sunucuyu kontrol edin.': 'Registration Failed! Check the server.',
      'Hatalı email veya şifre!': 'Invalid email or password!',
      'Oyuna bağlama': 'Link to game',
      'Vazgeç': 'Give Up',
      'İsim, Irk ve Sınıf alanları zorunludur.': 'Name, Race, and Class fields are required.',
      'Kaydet': 'Save',
      'Kapat': 'Close',
      'İptal': 'Cancel',
      'Oyun Başarıyla Oluşturuldu!': 'Game Created Successfully!',
      'Harita başarıyla veritabanına eklendi!': 'Map added to database successfully!',
      'Hata oluştu!': 'An error occurred!',
      'Önbellek başarıyla temizlendi!': 'Cache successfully cleared!',
      'Ayarlar': 'Settings',
      'Türkçe': 'Türkçe',
      'English': 'English',
      'Aydınlık veya karanlık mod': 'Light or dark mode',
      'Geçici verileri siler': 'Clears temporary data',
      'Çıkış Yap': 'Logout',
      'Hesabınızdan çıkış yapmak istediğinize emin misiniz?': 'Are you sure you want to log out of your account?',
      'Login': 'Login',
      'Register': 'Register',
      'Game Master': 'Game Master',
      'Player': 'Player',
      'Passwords do not match!': 'Passwords do not match!',
      'Please fill all fields': 'Please fill all fields',
      'Game successfully updated!': 'Game successfully updated!',
      'Update failed. Try again later.': 'Update failed. Try again later.',
      'Game invitation code': 'Game invitation code',
      'Max Player:': 'Max Player:',
      'Public Game': 'Public Game',
      'Save Changes': 'Save Changes',
      'Finish Campaing': 'Finish Campaign',
      'Are you sure you want to finish this campaign? This action cannot be undone!': 'Are you sure you want to finish this campaign? This action cannot be undone!',
      'Yes, end the game': 'Yes, end the game',
      'Game successfully finished!': 'Game successfully finished!',
      'End Campaing': 'End Campaign',
      'Linked Maps': 'Linked Maps',
      'Firstly a map has to be added to map pool!': 'Firstly a map has to be added to map pool!',
      'Map linked!': 'Map linked!',
      'No maps has been linked to this game.': 'No maps has been linked to this game.',
      'Game records & Notes': 'Game records & Notes',
      'Firstly a note has to be added to note pool!': 'Firstly a note has to be added to note pool!',
      'Added': 'Added',
      'Error occured while adding the note.': 'Error occured while adding the note.',
      'No notes has been added yet to this game.': 'No notes has been added yet to this game.',
      'New Note': 'New Note',
      'Delete Note?': 'Delete Note?',
      'Are you sure you want to delete this note?': 'Are you sure you want to delete this note?',
      'Cancel': 'Cancel',
      'Delete': 'Delete',
      'Back': 'Back',
      'Edit': 'Edit',
      'Create New Campaign': 'Create New Campaign',
      'Max Players:': 'Max Players:',
      'Visible to everyone in search results': 'Visible to everyone in search results',
      'Create Campaign': 'Create Campaign',
      'Game Archive': 'Game Archive',
      'Adventurers': 'Adventurers',
      'No players have joined this game.': 'No players have joined this game.',
      'Discovered Realms': 'Discovered Realms',
      'No maps have been added for this game.': 'No maps have been added for this game.',
      'Game Records & Notes': 'Game Records & Notes',
      'No note added for this campaign!': 'No note added for this campaign!',
      'No maps has been added yet.': 'No maps has been added yet.',
      'No notes has been added yet.': 'No notes has been added yet.',
      'See all notes': 'See all notes',
      'My Games': 'My Games',
      'Add New Map': 'Add New Map',
      'Pick from gallery': 'Pick from gallery',
      'Enter URL': 'Enter URL',
      'Open gallery': 'Open gallery',
      'Add map to pool': 'Add map to pool',
      'Map Pool': 'Map Pool',
      'You have successfully joined the game!': 'You have successfully joined the game!',
      'Find Games': 'Find Games',
      'Join': 'Join',
      'No public games have been created yet.': 'No public games have been created yet.',
      'My Joined Games': 'My Joined Games',
      'No notes have been created yet.': 'No notes have been created yet.',
      'Game Details': 'Game Details',
      'GM has not added a map to this game yet.': 'GM has not added a map to this game yet.',
      'CORE FEATURES': 'CORE FEATURES',
      'CLASS PROGRESSION': 'CLASS PROGRESSION',
      'Rule Books': 'Rule Books',
      'No data found.': 'No data found.',
      'CORE RULES & GUIDES': 'CORE RULES & GUIDES',
      'Dil / Language': 'Language',
      'Karanlık Tema': 'Theme',
      'Önbelleği Temizle': 'Clear Cache',
      'Change to GM View': 'Change to GM View',
      'Change to Player View': 'Change to Player View',
      'Notes': 'Notes',
      'Characters': 'Characters',
      'Create Game': 'Create Game',
      'My Maps': 'My Maps',
      'Logout': 'Logout',
      'Settings': 'Settings',
      'Join Game': 'Join Game',
      'NPCs': 'NPCs',
      'Games': 'Games',
      'Maps': 'Maps',
      'NPC Ekle': 'Add NPC',
      'Karakter Ekle': 'Add Character',
      'Karakter Resmi (Opsiyonel)': 'Character Image (Optional)',
      'İsim *': 'Name *',
      'Örn: Gandalf, Aragorn': 'E.g., Gandalf, Aragorn',
      'Irk (Race) *': 'Race *',
      'Sınıf (Class) *': 'Class *',
      'Seviye:': 'Level:',
      'Background': 'Background',
      'Alignment': 'Alignment',
      'Oyun (opsiyonel)': 'Game (Optional)',
      'Ability Scores': 'Ability Scores',
      'Standart: 10 | Modifier otomatik hesaplanır': 'Standard: 10 | Modifier is auto-calculated',
      'Combat Stats': 'Combat Stats',
      'Backstory (hikaye)': 'Backstory',
      'Karakterin geçmişi, motivasyonu...': 'Character\'s past, motivation...',
      'NPC eklendi!': 'NPC added!',
      'Karakter eklendi!': 'Character added!',
      'Kayıt sırasında hata oluştu.': 'An error occurred during save.',
      'Karakterlerim': 'My Characters',
      'Henüz NPC eklenmemiş.': 'No NPCs added yet.',
      'Henüz karakter eklenmemiş.': 'No characters added yet.',
      '+ butonuna basarak oluşturabilirsin!': 'Press the + button to create!',
      'Irk': 'Race',
      'Sınıf': 'Class',
      'Seviye': 'Level',
      'Backstory': 'Backstory',
      'Join to a Private Game': 'Join to a Private Game',
      'Ex: A7X9BQ': 'Ex: A7X9BQ',
      'Public Games': 'Public Games',
      'No description...': 'No description...',
      'Your Game': 'Your Game',
      'Already Joined': 'Already Joined',
      'World is full': 'World is full',
      'GM Notes': 'GM Notes',
      'Player Notes': 'Player Notes',
      'No adventure notes yet.': 'No adventure notes yet.',
      'Tap + to record your journey!': 'Tap + to record your journey!',
      'New GM Entry': 'New GM Entry',
      'New Player Log': 'New Player Log',
      'Title': 'Title',
      'e.g. The Mysterious Stranger': 'e.g. The Mysterious Stranger',
      'Category': 'Category',
      'Sub-Category (Optional)': 'Sub-Category (Optional)',
      'Details': 'Details',
      'Write down what happened...': 'Write down what happened...',
      'NPC': 'NPC',
      'Quest': 'Quest',
      'Loot': 'Loot',
      'Location': 'Location',
      'Combat': 'Combat',
      'Other': 'Other',
      'Villager': 'Villager',
      'Merchant': 'Merchant',
      'Guard': 'Guard',
      'Noble': 'Noble',
      'Wizard': 'Wizard',
      'Monster': 'Monster',
      'Main Story': 'Main Story',
      'Side Quest': 'Side Quest',
      'Bounty': 'Bounty',
      'Escort': 'Escort',
      'Gathering': 'Gathering',
      'Weapon': 'Weapon',
      'Armor': 'Armor',
      'Consumable': 'Consumable',
      'Gold/Valuables': 'Gold/Valuables',
      'Artifact': 'Artifact',
      'Village': 'Village',
      'City': 'City',
      'Cave': 'Cave',
      'Dungeon': 'Dungeon',
      'Forest': 'Forest',
      'Tavern': 'Taverna',
      'Encounter': 'Encounter',
      'Boss Fight': 'Boss Fight',
      'Trap': 'Trap',
      'Ambush': 'Ambush',
      'Lore': 'Lore',
      'Rumor': 'Rumor',
      'Puzzle': 'Puzzle',
      'Misc': 'Misc',
      'Campaign Title': 'Campaign Title',
      'Description': 'Description',
      'Map Name': 'Map Name',
      'Image URL': 'Image URL',
      'No maps have been added yet.': 'No maps have been added yet.',
      'Story has not been told...': 'Story has not been told...',
      'Unknown Hero': 'Unknown Hero',
      'Nameless Note': 'Nameless Note',
      'Players': 'Players',
      'Public': 'Public',
      'Private': 'Private',
      'No games have been created yet.': 'No games have been created yet.',
      'Edit game': 'Edit game',
      'Copy code': 'Copy code',
      'Game Name': 'Game Name',
      'Story / Description': 'Story / Description',
      'Oyuncu': 'Players',
      'Lv.': 'Lv.',
      'Races': 'Races',
      'Explore the diverse peoples of the world': 'Explore the diverse peoples of the world',
      'Classes': 'Classes',
      'Choose your path and abilities': 'Choose your path and abilities',
      'Equipment': 'Equipment',
      'Weapons, armor, tools, and adventuring gear': 'Weapons, armor, tools, and adventuring gear',
      'Monsters': 'Monsters',
      'Creatures, stats, legendary actions, and beasts': 'Creatures, stats, legendary actions, and beasts',
      'Spells': 'Spells',
      'Master the arcane and divine arts': 'Master the arcane and divine arts',
      'Everything you need to know about slots, concentration and components.': 'Everything you need to know about slots, concentration and components.',
      'Core rules for armor, weapons, wealth, and item management.': 'Core rules for armor, weapons, wealth, and item management.',
      'Rules for creature stats, sizes, challenge ratings, and actions.': 'Rules for creature stats, sizes, challenge ratings, and actions.',
      'Essential mechanics and shared traits every player should know.': 'Essential mechanics and shared traits every player should know.',
      'Email': 'Email',
      'Password': 'Password',
      'Select Role': 'Select Role',
      'Don\'t have an account? Register': 'Don\'t have an account? Register',
      'Username': 'Username',
      'Confirm Password': 'Confirm Password',
      'Already registered? Log in': 'Already registered? Log in',
    }
  };

  String translate(String key) {
    return _localizedValues[_currentLocale.languageCode]?[key] ?? key;
  }

  Future<void> loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final langCode = prefs.getString('language_code') ?? TR;
    _currentLocale = Locale(langCode);
    notifyListeners();
  }

  Future<void> changeLanguage(String langCode) async {
    _currentLocale = Locale(langCode);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', langCode);
    notifyListeners();
  }
}

extension LocalizationExtension on BuildContext {
  // context.tr('key') yazarak çeviriyi anında almamızı sağlar
  String tr(String key) => watch<LanguageManager>().translate(key);
}